---
services:
  bot:
    container_name: oc-ref-bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./oc_ref_bot:/oc_ref_bot
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
