[build-system]
requires = ['hatchling']
build-backend = 'hatchling.build'

[tool.hatch.version]
path = "oc_ref_bot/__init__.py"

[tool.hatch.build.targets.sdist]
include = ["oc_ref_bot"]

[project]
name = "oc_ref_bot"
requires-python = ">=3.12"
dynamic = ["version"]
dependencies = [
    "aiogram==3.12.*",
    "pydantic-settings==2.4.*",
    "SQLAlchemy==1.4.*",
    "aiopg==1.4.*",
    "sentry-sdk==2.13.*",
    "numpy==2.2.*",
    "opencv-python==4.11.0.*",
    "pillow==11.1.*"
]

[project.optional-dependencies]
test = [
    "ruff",
]

[project.scripts]
start-bot = "oc_ref_bot.main:main"

[tool.black]
line-length = 120
target-version = ['py312']

[tool.ruff]
line-length = 120
target-version = "py312"
exclude = [".venv"]

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
select = [
    "ANN001",
    "ANN201",
    "ANN202",
    "ANN204",
    "ANN206",
    "A",
    "ARG",
    "B904",
    "BLE",
    "C",
    "COM",
    "E",
    "ERA",
    "F",
    "FBT",
    "I",
    "ISC",
    "W",
    "N",
    "NPY",
    "PD",
    "PIE",
    "PLC",
    "PLE",
    "PLR",
    "PLW",
    "RET",
    "RSE",
    "RUF",
    "Q",
    "SIM",
    "T",
    "TCH",
    "UP",
    "DTZ001",
    "DTZ005",
    "DTZ006",
    "DTZ007",
    "DTZ012",
]
ignore = ["COM812", "RUF001", "RUF100", "RUF003"]
